[package]
name = "just_state"
version = "0.1.3"
edition = "2021"
license = "MIT"
description = "justjs state manager"

[dependencies]
colored = "2.0.0"
lazy_static = "1.4.0"
serde = "1.0.152"
macros = { path = "../macros" }