[package]
name = "just_state"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "justjs state manager"

[dependencies]
# local
macros = { package = "macros-rs", path = "../macros", version = "0.4.0" }

# ext
colored = "2.0.0"
lazy_static = "1.4.0"
serde = "1.0.152"
clap = "4.1.4"
