[package]
name = "core_js"
version = "0.1.1"
edition = "2021"

[dependencies]
deno_core = "0.142.0"
tokio = { version = "1.19.2", features = ["full"] }
duration-string = "0.1.1" 
colored = "2"
psutil = "3.2.2"
libc = "0.2.137"
sysinfo = "0.26.7"
v_htmlescape = "0.15.8"
