[package]
name = "just"
version = "0.4.2"
edition = "2021"

[dependencies]
deno_core = "0.160.0"
tokio = { version = "1.19.2", features = ["full"] }
duration-string = "0.1.1" 
colored = "2"
psutil = "3.2.2"
libc = "0.2.137"
sysinfo = "0.26.7"
v_htmlescape = "0.15.8"
dirs = "4.0.0"
hostname = "^0.3"
reqwest = { version = "0.11.12", features = ["blocking"] } 
nanoid = "0.4.0"
staticfile = "0.5.0"
mount = "0.4.0"
iron = "0.6.1"
shell = { git = "https://github.com/google/rust-shell" }
sqlite = "0.30.1"
serde = "1.0.147"
serde_json = "1.0.87"
serde_yaml = "0.9.14"
home = "0.5.4"
clap = { version = "4.0.27", features = ["derive"] }
rustyline = "9.1.2"
sha2 = "0.10.6"
data-encoding = "2.3.2"
inquire = "0.5.2"
question = "0.2.2"
data-url = "0.2.0"
terminal-spinners = "0.3.2"
thread_local = "1.1.4"
regex = "1.7.0"
termion = "1.5.6"
url = "2.3.1"
normalize-path = "0.2.0"

[build-dependencies]
chrono = "0.4.23"
sha2 = "0.10.6"
data-encoding = "2.3.2"
deno_core = "0.160.0"
