[package]
name = "core_js"
version = "0.2.0"
edition = "2021"

[dependencies]
deno_core = "0.152.0"
tokio = { version = "1.19.2", features = ["full"] }
duration-string = "0.1.1" 
colored = "2"
psutil = "3.2.2"
libc = "0.2.137"
sysinfo = "0.26.7"
v_htmlescape = "0.15.8"
dirs = "4.0.0"
hostname = "^0.3"
reqwest = "0.11.12"
nanoid = "0.4.0"
staticfile = "0.5.0"
mount = "0.4.0"
iron = "0.6.1"
