[env]
JUST_PATH = "%{dir.home}/Developer/rust/js_runtime"

[tasks._publish_macros]
info = "helper for publish"
path = "crates/macros"
script = "cargo publish --no-verify --allow-dirty"

[tasks._publish_state]
info = "helper for publish"
path = "crates/state"
script = "cargo publish --no-verify --allow-dirty"

[tasks._test_no-verify]
info = "helper for test-all"
path = "tests/new"
script = "%{env.JUST_PATH}/just run %{arg.1} -A"

[tasks]
clean = { info = "remove binary", path = "", script = "rm just" }
build = { info = "build just", path = "", script = ["cargo build --release", "mv %{env.JUST_PATH}/target/release/just %{env.JUST_PATH}"] }
publish = { info = "publish crates", path = "", script = ["maid _publish_macros -q", "maid _publish_state -q"] }
test = { info = "run js tests", path = "tests/new", script = ["maid build", "%{env.JUST_PATH}/just run %{arg.1} -A"] }
test-all = { info = "run all js tests", path = "", script = "bash -c 'for file in tests/new/*.js; do maid _test_no-verify ${file#*/*/} -q; done'" }
test-all-build = { info = "run all js tests", path = "", script = ["maid build", "bash -c 'for file in tests/new/*.js; do maid _test_no-verify ${file#*/*/} -q; done'"] }