name: project
description: the project desc
version: 0.0.1
author: john@example.com
url: example.com
repository: github.com/example/example
license: mit
index: tests/cmd.js
tasks:
  start/uuid: ./just run tests/uuid.js
  benchmark: ./just run tests/bench.js
  console: ./just run tests/console.js
dependencies:
  test: 0.0.1
